### ISSUE TITLE
[request] Remove checkpoints and LFS from the repositories

### ISSUE THREAD

**Issue by Trev57** [riffusion/riffusion-inference#11]
It would be much faster, as well as more readily working if they were uploaded to a file sharing site. The LFS files seem to always fail to download, and for some reason bluescreen my computer. I have seen others with similar problems downloading, and so I think this would help fix some of the troubleshooting issues people have

**Comment by hmartiro** [comment]
Are you talking about this repository or the huggingface checkpoint? This repo should not contain any checkpoints, just a few small images

**Comment by Trev57** [comment]
the hugging face checkpoint, apologies i should have specified

**Comment by hmartiro** [comment]
I'm not sure exactly what the problem is, but as I understand storing the checkpoint as a huggingface model is totally standard, so not inclined to change it. For example see the source model: https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main
