### ISSUE TITLE
Finetuning guide and training code

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [riffusion/riffusion-inference#2]
Having a bit of trouble finding this, but I have a lot of ideas about how to finetune this and was looking for instructions on training. I think we can get to songs of any length pretty easily by converting the model to the modified one for outpainting and retraining on 512x1024.

**Comment by DenisSergeevitch** [comment]
Also want to do a finetune; please share a code if it is possible

**Comment by chavinlo** [comment]
Hi Jonny
and yes I am also interested

**Comment by chavinlo** [comment]
I can provide you with some GPU compute if needed
Either distributed (https://github.com/chavinlo/distributed-diffusion one of my side projects)
Or local (A100s) but only for a while

**Comment by oxysoft** [comment]
Do you guys think we could fine-tune this with dreambooth as usual? It seems unlikely to me that this was trained on copyrighted music but don't worry, you can put the steps up for fine-tuning and a bunch of useful idiots like me will take the hit for you.

**Comment by hmartiro** [comment]
Additional fine tuning and data information has been added to the model-card. This was trained using approaches similar to hugging face examples, but fine-tuning can be achieved with very small datasets using a dreambooth approach. Will look to add tools to make fine tuning on your own data simpler.
