### ISSUE TITLE
Fine tuning the model possible?

### ISSUE THREAD

**Issue by rhelsing** [riffusion/riffusion-inference#29]
It would be great if there was a simple path for fine-tuning the model. Much like what dance diffusion offers.

**Comment by hmartiro** [comment]
Additional fine tuning and data information has been added to the model-card. This was trained using approaches similar to hugging face examples, but fine-tuning can be achieved with very small datasets using a dreambooth approach. Will look to add tools to make fine tuning on your own data simpler.
