### ISSUE TITLE
What data was used to train riffusion?

### ISSUE THREAD

**Issue by alextamkin** [riffusion/riffusion-inference#5]
Super cool work! Could you provide more information about the data source used to train riffusion?

For example:
* How much audio data did you use for finetuning?
* What's the source of the audio data?
* How did you get the paired text with the audio? (e.g. is it extracted from the tags or music description?)

Thanks so much!

**Comment by scf4** [comment]
Yes it would be interesting.

On an entirely unrelated note, having dealt with them in the past, some Recording Industry Associations are technically inept (or obtuse) and absolutely ruthless when it comes to perceived IP infringement.

I once received a takedown request for a user's post that linked to Drake's Instagram else the well-known hosting service I used at the time was going to suspend my account. Sorry for the tangent.

Back on topic, datasets are cool I agree.

**Comment by oxysoft** [comment]
@scf4 Public figures working in ML like the authors of Riffusion should stick to royalty free datasets. The strategy for AI music will be to make fine-tuning really easy and available to all, easy enough for a 12 y/o to do it comfortably just by following a few easy steps. 12 y/o kids don't care about copyrights, it will be limewire all over again and this time the music industry will be utterly powerless.

**Comment by karen-pal** [comment]
I've opened a similiar issue on the app's repository: https://github.com/hmartiro/riffusion-app/issues/12

Dataset info is very important and will open doors for creators everywhere.

**Comment by enn-nafnlaus** [comment]
I understand why they don't disclose it, though - to them, it just invites possible headaches.

**Comment by hmartiro** [comment]
Additional fine tuning and data information has been added to the model-card. This was trained using approaches similar to hugging face examples, but fine-tuning can be achieved with very small datasets using a dreambooth approach. Will look to add tools to make fine tuning on your own data simpler.

**Comment by happypepper** [comment]
> @scf4 Public figures working in ML like the authors of Riffusion should stick to royalty free datasets. The strategy for AI music will be to make fine-tuning really easy and available to all, easy enough for a 12 y/o to do it comfortably just by following a few easy steps. 12 y/o kids don't care about copyrights, it will be limewire all over again and this time the music industry will be utterly powerless.

If you check out OpenAI's jukebox project, they've clearly trained with copyrighted music and don't really care.

**Comment by dustyny** [comment]
> @scf4 Public figures working in ML like the authors of Riffusion should stick to royalty free datasets. The strategy for AI music will be to make fine-tuning really easy and available to all, easy enough for a 12 y/o to do it comfortably just by following a few easy steps. 12 y/o kids don't care about copyrights, it will be limewire all over again and this time the music industry will be utterly powerless.

It's well understood at this moment that the current copyright laws are lagging behind (as they always do), we don't know what they will be when the finally do land. Just like with Napster when the laws do catch up, the issue will be addressed. 

Please let's not turn a git repo comment section into a political driven debate on ethics.  I'd recommend Reddit if you want to argue or Quora if you explore the legal, ethical & philosophical ramifications; there is more then enough of these discussions  there..

**Comment by breadbrowser** [comment]
> > @scf4 Public figures working in ML like the authors of Riffusion should stick to royalty free datasets. The strategy for AI music will be to make fine-tuning really easy and available to all, easy enough for a 12 y/o to do it comfortably just by following a few easy steps. 12 y/o kids don't care about copyrights, it will be limewire all over again and this time the music industry will be utterly powerless.
> 
> If you check out OpenAI's jukebox project, they've clearly trained with copyrighted music and don't really care.

openai can get rights to them.

**Comment by jbmaxwell** [comment]
I was also curious about the initial training. I'm not so bothered about specifics of the dataset (though general info on size would help) but more about training params (lr, bs, etc.) and duration (epochs/steps).
